import type { Article } from "../types";
const a: Article = {
  slug: "mejores-deshumidificadores",
  title: "Los mejores deshumidificadores de 2026: cuántos litros necesitas y cuál comprar",
  description: "Cómo elegir deshumidificador para casa: capacidad real por habitación, ruido, consumo y drenaje, con los modelos de De'Longhi, Pro Breeze, Comfee y Cecotec que merecen la pena.",
  category: "clima",
  date: "2026-09-04",
  readingMinutes: 9,
  intro: [
    "Cuando llegan las lluvias y baja la temperatura, la humedad en casa se nota en las ventanas empañadas, la ropa que no seca y ese olor a cerrado en los armarios. Un deshumidificador bien elegido lo resuelve, pero uno mal dimensionado no para de funcionar y apenas se nota.",
    "La cifra de litros al día que anuncian los fabricantes se mide en condiciones extremas de laboratorio. En una casa española normal, un aparato de 12 litros extrae entre 3 y 6 al día. Esta guía te ayuda a calcular lo que necesitas y elige modelos que cumplen en ruido y consumo, que son los dos factores que más pesan a diario.",
  ],
  quickPick: [
    { label: "Mejor en general", product: "De'Longhi Tasciugo AriaDry DEX214F" },
    { label: "Mejor calidad-precio", product: "Cecotec Big Dry 4000 Expert" },
    { label: "Más silencioso", product: "Pro Breeze 12 L" },
    { label: "Casas grandes", product: "COLAZE 20 L" },
    { label: "Económico", product: "Comfee 12 L" },
  ],
  criteria: [
    { title: "Capacidad según la estancia", text: "Para un dormitorio o una habitación de hasta 20 m² basta con 10 a 12 litros al día. Para un salón grande o un piso entero con puertas abiertas, entre 16 y 20 litros. Si el problema es un sótano o mucha condensación, ve directamente a 20 litros." },
    { title: "Ruido", text: "Un deshumidificador funciona horas seguidas, así que el ruido importa. Por debajo de 40 dB en modo bajo se puede dormir con él; los de 45 dB o más se relegan al pasillo." },
    { title: "Consumo", text: "Entre 200 y 300 W en los de compresor. A 8 horas al día, unos 0,40 euros diarios. Un higrostato que apague el aparato al llegar a la humedad objetivo es lo que más ahorra." },
    { title: "Depósito y drenaje continuo", text: "Un depósito de 2 litros se llena en una noche en un ambiente muy húmedo. La salida para manguera permite dejarlo funcionando sin vaciar." },
  ],
  products: [
    { name: "De'Longhi Tasciugo AriaDry Multi DEX214F", badge: "Mejor en general", priceRange: "180-250 €", searchQuery: "De'Longhi Tasciugo AriaDry DEX214F deshumidificador",
      summary: "Silencioso, eficiente y con función de secado de ropa que de verdad funciona. Extrae hasta 14 litros en laboratorio con un consumo contenido, tiene drenaje continuo y filtro lavable. Es el que compraríamos para un piso completo.",
      pros: ["Muy silencioso", "Función de secado de ropa", "Consumo contenido", "Drenaje continuo"],
      cons: ["Precio por encima de la media", "Depósito mediano"],
      idealFor: "Pisos de tamaño medio con problemas de humedad en varias habitaciones." },
    { name: "Cecotec Big Dry 4000 Expert", badge: "Mejor calidad-precio", priceRange: "110-150 €", searchQuery: "Cecotec Big Dry 4000 Expert deshumidificador",
      summary: "Cumple con lo esencial a un precio muy razonable: buena extracción, higrostato, temporizador y depósito de tamaño correcto. Es algo más ruidoso que el De'Longhi, pero para un uso de día en el salón es una compra muy sensata.",
      pros: ["Precio ajustado", "Higrostato y temporizador", "Servicio técnico en España"],
      cons: ["Ruido medio", "Diseño algo voluminoso"],
      idealFor: "Quien quiere resultados sin pagar la gama alta." },
    { name: "Pro Breeze 12 L", badge: "Más silencioso", priceRange: "120-170 €", searchQuery: "Pro Breeze deshumidificador 12L silencioso",
      summary: "Es de los pocos de compresor que se pueden dejar en un dormitorio por la noche. Extrae de forma constante, tiene ruedas, higrostato digital y salida de drenaje. Buena fiabilidad y una de las valoraciones más altas de la categoría.",
      pros: ["Muy silencioso en modo bajo", "Fácil de mover", "Higrostato digital"],
      cons: ["Depósito de 2 litros se llena rápido", "Sin secado de ropa dedicado"],
      idealFor: "Dormitorios y despachos donde el ruido es lo primero." },
    { name: "COLAZE 20 L", badge: "Casas grandes", priceRange: "90-130 €", searchQuery: "COLAZE deshumidificador 20L",
      summary: "Mucha capacidad por poco dinero. Cubre prácticamente cualquier estancia doméstica, tiene drenaje continuo y su coste por litro extraído es de los más bajos. No es el más silencioso ni el más bonito, pero para un piso grande o un bajo con humedad es muy eficaz.",
      pros: ["Gran capacidad", "Precio muy competitivo", "Drenaje continuo"],
      cons: ["Ruido medio-alto", "Marca menos conocida"],
      idealFor: "Pisos grandes, bajos y espacios con mucha humedad." },
    { name: "Comfee 12 L", badge: "Económico", priceRange: "90-120 €", searchQuery: "Comfee deshumidificador 12L",
      summary: "La opción de entrada de una marca del grupo Midea, con extracción correcta, higrostato y ruedas. Cumple para una habitación o un piso pequeño y suele estar en oferta.",
      pros: ["Precio bajo", "Funciones básicas completas", "Compacto"],
      cons: ["Menos silencioso que Pro Breeze", "Acabados sencillos"],
      idealFor: "Habitaciones sueltas o pisos pequeños con presupuesto ajustado." },
  ],
  buyingTips: [
    "Apunta a una humedad del 50 al 55 por ciento: por debajo del 40 el aire reseca y por encima del 60 aparecen mohos.",
    "Coloca el aparato en el centro de la estancia, lejos de paredes, para que el aire circule.",
    "Limpia el filtro cada dos semanas; un filtro sucio dispara el consumo y baja la extracción.",
    "Si lo vas a dejar toda la noche, elige un modelo con drenaje continuo o un depósito de al menos 3 litros.",
  ],
  faq: [
    { q: "¿Deshumidificador de compresor o de desecante?", a: "Compresor para viviendas con temperaturas normales: es más eficiente. Desecante solo en espacios muy fríos, por debajo de 10 grados, como garajes o trasteros." },
    { q: "¿Cuánto gasta al mes?", a: "Un modelo de 250 W funcionando 8 horas al día consume unos 60 kWh al mes, entre 10 y 15 euros según la tarifa. Con higrostato, bastante menos." },
    { q: "¿Sirve para secar la ropa?", a: "Sí, si lo colocas junto al tendedero en una habitación cerrada. Los modelos con modo de secado de ropa aceleran el proceso notablemente." },
  ],
  conclusion: "El De'Longhi DEX214F es el más completo y silencioso para un piso entero. Con menos presupuesto, el Cecotec Big Dry 4000 Expert cumple con creces. Para un dormitorio, el Pro Breeze 12 L es el que mejor se lleva con el sueño, y para pisos grandes o bajos húmedos, el COLAZE 20 L da más capacidad por euro que ningún otro.",
};
export default a;
