import type { Article } from "../types";
const a: Article = {
  slug: "mejores-freidoras-de-aire",
  title: "Las mejores freidoras de aire de 2026 por tamaño de familia y presupuesto",
  description: "Guía práctica para elegir freidora de aire: qué capacidad necesitas, cuánto consume de verdad y qué modelos de Cosori, Cecotec, Ninja y Xiaomi merecen la pena.",
  category: "cocina",
  date: "2026-09-10",
  readingMinutes: 10,
  intro: [
    "La freidora de aire es el pequeño electrodoméstico que más ha cambiado la cocina diaria en España en los últimos años, y no por moda: calienta más rápido que el horno, gasta menos y limpia mejor. Pero el mercado está saturado de modelos y las diferencias reales no están en el número de programas, sino en la capacidad, la potencia y lo fácil que sea limpiar la cesta.",
    "Aquí seleccionamos modelos por tamaño de hogar y presupuesto, con lo que se puede esperar de cada uno en el día a día. Las capacidades en litros que anuncian las marcas son generosas; en la práctica, cuenta con un litro por persona más un litro de margen.",
  ],
  quickPick: [
    { label: "Mejor en general", product: "Cosori TurboBlaze 6 L" },
    { label: "Mejor calidad-precio", product: "Cecotec Cecofry Duoheat 4000" },
    { label: "Para 1 o 2 personas", product: "Ninja CRISPi" },
    { label: "Familias grandes", product: "Cosori Práctica 6,2 L" },
    { label: "Diseño", product: "CREATE Studio Crystal" },
  ],
  criteria: [
    { title: "Capacidad real", text: "Para una o dos personas, entre 3,5 y 4 litros. Para tres o cuatro, de 5 a 7 litros. Una cesta demasiado pequeña obliga a cocinar en tandas y pierde la gracia de la rapidez." },
    { title: "Potencia y distribución del calor", text: "Entre 1.500 y 1.800 W es lo habitual. Más potencia no siempre significa mejor: importa que el ventilador reparta bien el aire para que las patatas queden crujientes sin remover cada tres minutos." },
    { title: "Limpieza", text: "Cesta y rejilla aptas para lavavajillas y con antiadherente de calidad. Es el factor que más pesa a los tres meses de uso." },
    { title: "Ruido y consumo", text: "Todas hacen ruido de ventilador, pero las de motor sin escobillas son claramente más silenciosas. En consumo, una sesión de 20 minutos ronda los 0,5 kWh, muy por debajo de un horno convencional." },
  ],
  products: [
    { name: "Cosori TurboBlaze 6 L", badge: "Mejor en general", priceRange: "110-150 €", searchQuery: "Cosori TurboBlaze 6L freidora de aire",
      summary: "Es la referencia de la gama media-alta: calienta rápido, reparte el aire mejor que la mayoría y su motor es de los más silenciosos. La cesta cuadrada aprovecha bien el espacio y se limpia sin esfuerzo. Si vais tres o cuatro en casa y queréis un modelo para años, es la compra segura.",
      pros: ["Muy rápida y uniforme", "Motor silencioso", "Cesta grande y fácil de limpiar", "Control de temperatura preciso"],
      cons: ["Ocupa bastante en la encimera", "Precio por encima de la media"],
      idealFor: "Hogares de tres o cuatro personas que la usarán a diario." },
    { name: "Cecotec Cecofry Duoheat 4000", badge: "Mejor calidad-precio", priceRange: "60-90 €", searchQuery: "Cecotec Cecofry Duoheat 4000",
      summary: "La opción sensata para quien no quiere gastar mucho. Su sistema de calor por arriba y por abajo consigue resultados muy parejos, tiene ventana para mirar sin abrir y su capacidad es suficiente para dos o tres personas.",
      pros: ["Precio muy ajustado", "Cocina uniforme para su gama", "Ventana y luz interior"],
      cons: ["Algo más ruidosa que las de gama alta", "Antiadherente algo menos duradero"],
      idealFor: "Parejas o primeras freidoras con presupuesto contenido." },
    { name: "Ninja CRISPi", badge: "Para 1 o 2 personas", priceRange: "150-200 €", searchQuery: "Ninja CRISPi freidora de aire",
      summary: "Un concepto distinto: el motor se acopla a recipientes de vidrio que sirven para cocinar, guardar y llevar. Es cara para su capacidad, pero para una persona o una pareja que cocine raciones pequeñas y valore el espacio es una solución muy práctica.",
      pros: ["Recipientes de vidrio que van al lavavajillas y a la nevera", "Ocupa poco", "Resultados muy buenos en raciones pequeñas"],
      cons: ["Precio alto para su capacidad", "No sirve para familias"],
      idealFor: "Personas solas o parejas con cocinas pequeñas." },
    { name: "Cosori Práctica 6,2 L", badge: "Familias", priceRange: "90-120 €", searchQuery: "Cosori 6.2L freidora de aire",
      summary: "Más sencilla que la TurboBlaze pero con mucha capacidad por menos dinero. Programas básicos, buena potencia y cesta grande. Si lo que necesitas es volumen para cuatro o cinco raciones sin pagar la gama alta, encaja.",
      pros: ["Gran capacidad", "Buena relación tamaño y precio", "Manejo simple"],
      cons: ["Menos rápida que la TurboBlaze", "Diseño más básico"],
      idealFor: "Familias que priorizan capacidad sobre funciones." },
    { name: "CREATE Studio Crystal", badge: "Diseño", priceRange: "80-110 €", searchQuery: "CREATE Studio Crystal freidora de aire",
      summary: "La freidora que se puede dejar a la vista. Cuerpo transparente, buen tamaño y resultados correctos. No es la más rápida ni la más potente, pero cumple y queda bien en cocinas abiertas.",
      pros: ["Estética cuidada y ventana panorámica", "Capacidad adecuada para 2 o 3 personas", "Fácil de usar"],
      cons: ["Rendimiento algo por detrás de Cosori", "Menos accesorios"],
      idealFor: "Quien valora el diseño y cocina raciones medianas." },
  ],
  buyingTips: [
    "Calcula la capacidad por personas, no por lo que dice la caja: un litro por comensal más uno de margen.",
    "Comprueba que cesta y rejilla vayan al lavavajillas. Es lo que decide si la usas a diario o la abandonas.",
    "No compres por número de programas; con temperatura y tiempo manuales haces exactamente lo mismo.",
    "Si tienes poca encimera, mide antes: los modelos de 6 litros ocupan como un microondas pequeño.",
  ],
  faq: [
    { q: "¿Una freidora de aire fríe de verdad?", a: "No fríe: es un horno pequeño con un ventilador potente. Consigue un exterior crujiente con muy poco aceite, pero la textura no es idéntica a la fritura en aceite." },
    { q: "¿Cuánto gasta comparada con un horno?", a: "Una sesión de 20 minutos consume alrededor de medio kilovatio hora. Un horno convencional necesita precalentar y suele gastar el doble o el triple para la misma tarea." },
    { q: "¿Merecen la pena las de doble cesta?", a: "Solo si sueles cocinar dos cosas a la vez con tiempos distintos. Para el uso habitual, una cesta grande es más versátil y fácil de limpiar." },
  ],
  conclusion: "La Cosori TurboBlaze 6 L es la que mejor equilibra rapidez, silencio y limpieza para una familia. Con menos presupuesto, la Cecotec Duoheat 4000 da resultados muy dignos. Y si vives solo o en pareja, mira la Ninja CRISPi antes de comprar una freidora grande que acabará medio vacía.",
};
export default a;
