import type { Article } from "../types";
const a: Article = {
  slug: "mejores-purificadores-de-aire",
  title: "Los mejores purificadores de aire de 2026 para alergias, polvo y olores",
  description: "Cómo elegir purificador de aire con filtro HEPA según los metros de la estancia, con modelos de Levoit, AEG, Cecotec y Philips y el coste real de los filtros.",
  category: "clima",
  date: "2026-08-27",
  readingMinutes: 9,
  intro: [
    "Un purificador de aire no es un gadget: en casas con alergias, mascotas o cerca de calles con tráfico marca la diferencia en cómo se respira y cómo se duerme. Pero para que funcione tiene que estar bien dimensionado para la habitación y tener un filtro HEPA de verdad, no una malla con nombre bonito.",
    "En esta guía explicamos cómo calcular el tamaño, qué significa el CADR y cuánto cuestan los filtros de recambio, que es el gasto que muchos olvidan. Después, cinco modelos que cumplen en cada franja.",
  ],
  quickPick: [
    { label: "Mejor en general", product: "Levoit Core 300S" },
    { label: "Alergias", product: "AEG Pure 5000" },
    { label: "Mejor calidad-precio", product: "Cecotec TotalPure" },
    { label: "Dormitorio pequeño", product: "Levoit Core Mini" },
    { label: "Silencioso y fiable", product: "Philips serie 800" },
  ],
  criteria: [
    { title: "Metros y CADR", text: "El CADR indica cuántos metros cúbicos de aire limpia por hora. Para una habitación de 20 m² necesitas un CADR de al menos 150 m³/h para renovar el aire varias veces por hora. Compra siempre para más metros de los que tienes: lo usarás en modo bajo y hará menos ruido." },
    { title: "Filtro HEPA real", text: "Busca HEPA H13 o superior. Retiene el 99,95 por ciento de partículas de 0,3 micras, incluidas polen, ácaros y humo. Los filtros 'tipo HEPA' no cumplen esa norma." },
    { title: "Coste de los filtros", text: "Un filtro dura entre 6 y 12 meses y cuesta entre 20 y 50 euros. En cinco años, los filtros pueden costar más que el aparato. Comprueba precio y disponibilidad antes de comprar." },
    { title: "Ruido y sensores", text: "Para dormitorio, menos de 30 dB en modo bajo. Un sensor de calidad del aire con modo automático evita tenerlo a tope sin necesidad." },
  ],
  products: [
    { name: "Levoit Core 300S", badge: "Mejor en general", priceRange: "100-150 €", searchQuery: "Levoit Core 300S purificador de aire",
      summary: "El purificador más recomendado por buenas razones: filtro HEPA H13, muy silencioso en modo nocturno, app con sensor de calidad del aire y filtros de recambio fáciles de encontrar. Cubre bien una habitación de 20 a 40 m².",
      pros: ["HEPA H13 real", "Muy silencioso de noche", "App y modo automático", "Filtros baratos y disponibles"],
      cons: ["Sin pantalla de valores detallados", "Para salones grandes se queda corto"],
      idealFor: "Dormitorios y despachos de hasta 40 m²." },
    { name: "AEG Pure 5000", badge: "Alergias", priceRange: "180-260 €", searchQuery: "AEG Pure 5000 purificador de aire",
      summary: "Compacto pero con filtrado de alto rendimiento y un sistema inteligente que ajusta la potencia solo. Para personas alérgicas es de los más efectivos, con consumo muy bajo y Wi-Fi.",
      pros: ["Filtrado muy eficaz contra alérgenos", "Modo inteligente y Wi-Fi", "Consumo muy bajo"],
      cons: ["Precio alto", "Filtros de marca algo caros"],
      idealFor: "Alérgicos y hogares con polen o ácaros como problema principal." },
    { name: "Cecotec TotalPure", badge: "Mejor calidad-precio", priceRange: "90-140 €", searchQuery: "Cecotec TotalPure purificador de aire",
      summary: "Filtro HEPA 13, buena cobertura y, en la versión conectada, control desde app. Algunos modelos además refrescan o calientan, lo que resuelve dos aparatos en uno. Servicio técnico en España.",
      pros: ["Precio contenido", "Versiones con ventilador y calor", "Soporte nacional"],
      cons: ["Más ruidoso que Levoit en modo alto", "Diseño menos discreto"],
      idealFor: "Quien quiere purificar y climatizar con un solo aparato." },
    { name: "Levoit Core Mini", badge: "Dormitorio pequeño", priceRange: "40-60 €", searchQuery: "Levoit Core Mini purificador",
      summary: "Muy pequeño, muy silencioso y con consumo mínimo. No pretende limpiar un salón, pero en una habitación de 10 o 15 m² funciona y cuesta menos que una cena. Ideal para probar si un purificador te ayuda.",
      pros: ["Precio muy bajo", "Silencio casi total", "Ocupa como una botella"],
      cons: ["Solo estancias pequeñas", "Sin sensor de calidad del aire"],
      idealFor: "Dormitorios pequeños, despachos y habitaciones infantiles." },
    { name: "Philips serie 800", badge: "Silencioso y fiable", priceRange: "120-170 €", searchQuery: "Philips purificador de aire serie 800",
      summary: "Sensor de partículas con indicador en el propio aparato, filtrado eficaz y muy poco ruido. Philips tiene una red de recambios amplia y una fiabilidad contrastada. Buena elección para quien no quiere apps.",
      pros: ["Sensor con lectura en pantalla", "Muy silencioso", "Marca fiable con recambios fáciles"],
      cons: ["Sin app en el modelo básico", "Cobertura media"],
      idealFor: "Dormitorios y salas medianas donde se busca sencillez y silencio." },
  ],
  buyingTips: [
    "Elige un modelo para el doble de metros de tu habitación: trabajará en modo bajo, silencioso y con menos desgaste del filtro.",
    "Colócalo a medio metro de la pared y sin obstáculos alrededor para que el aire circule.",
    "Aspira o cepilla el prefiltro cada dos semanas; alarga la vida del HEPA.",
    "Contra olores fuertes, busca una capa de carbón activo generosa, no una fina lámina.",
  ],
  faq: [
    { q: "¿Sirve un purificador contra el polen?", a: "Sí, es uno de los usos donde más se nota. Con ventanas cerradas, un HEPA H13 reduce mucho la concentración en la habitación." },
    { q: "¿Cuánto tiempo debe estar encendido?", a: "Lo ideal es dejarlo en modo automático todo el día. Consume muy poco, entre 5 y 30 W en modos bajos." },
    { q: "¿Quita los virus del aire?", a: "Un filtro HEPA retiene partículas en las que viajan los virus, pero no es una medida sanitaria por sí sola. Ayuda; no sustituye a ventilar." },
  ],
  conclusion: "El Levoit Core 300S es la compra más segura para una habitación normal. Con alergias fuertes, el AEG Pure 5000 justifica el extra. Si el presupuesto es corto, el Levoit Core Mini permite comprobar si un purificador te ayuda gastando muy poco.",
};
export default a;
